sudo: required
dist: trusty
language: python
python:
 - "2.7"
 - "3.6"
env:
  global:
     - LD_LIBRARY_PATH=/usr/lib/llvm-5.0/lib
     - LLVM_HOME=/usr/lib/llvm-5.0
before_install:
  - sudo apt-get update -y
  - sudo apt-get install libclang-5.0 clang-5.0 -y
install:
  - pip install .
script:
  - python setup.py test
