sudo: required
dist: xenial
language: python
python:
 - "3.7"
 - "3.8"
env:
  global:
    - LD_LIBRARY_PATH=/usr/lib/llvm-10.0/lib
    - LLVM_HOME=/usr/lib/llvm-10.0
    - CC=clang-10.0
    - CXX=clang++-10.0
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-10.0
    packages:
      - clang-10.0
      - libclang-10.0
      - llvm-10.0
      - llvm-10.0-dev
install:
  - pip install .
script:
  - python setup.py test
