sudo: required
dist: xenial
language: python
python:
 - "3.7"
 - "3.8"
git:
  depth: 1
env:
  global:
    - LD_LIBRARY_PATH=/usr/lib/llvm-10/lib
    - LLVM_HOME=/usr/lib/llvm-10
    - CC=clang-10
    - CXX=clang++-10
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - clang-10
      - libclang-10-dev 
      - libclang-cpp10
      - libclang-cpp10-dev
      - llvm-10
      - llvm-10-dev
      - llvm-10-tools
install:
  - pip install .
script:
  - python setup.py test
